In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### Reading the data file in df

**Read the csv data file and disply its head**

In [46]:
df=pd.read_csv("mammographic_masses_data_clean.csv")
df.head()

   BI-RADS  Age  Shape  Margin  Density  Target
0        5   67      3       5        3       1
1        5   58      4       5        3       1
2        4   28      1       1        3       0
3        5   57      1       5        3       1
4        5   76      1       4        3       1

   BI-RADS  Age  Shape  Margin  Density  Target
0        5   67      3       5        3       1
1        5   58      4       5        3       1
2        4   28      1       1        3       0
3        5   57      1       5        3       1
4        5   76      1       4        3       1

**How many data entries you have?**

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   BI-RADS  830 non-null    int64
 1   Age      830 non-null    int64
 2   Shape    830 non-null    int64
 3   Margin   830 non-null    int64
 4   Density  830 non-null    int64
 5   Target   830 non-null    int64
dtypes: int64(6)
memory usage: 39.0 KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 6 columns):
BI-RADS    830 non-null int64
Age        830 non-null int64
Shape      830 non-null int64
Margin     830 non-null int64
Density    830 non-null int64
Target     830 non-null int64
dtypes: int64(6)
memory usage: 39.0 KB

**Which type of cancer is common?**

In [49]:
df.Target.value_counts()

0    427
1    403
Name: Target, dtype: int64

0    427
1    403
Name: Target, dtype: int64

**Reproduce the output to show some statistics**

In [50]:
df.describe()

          BI-RADS         Age       Shape      Margin     Density      Target
count  830.000000  830.000000  830.000000  830.000000  830.000000  830.000000
mean     4.393976   55.781928    2.781928    2.813253    2.915663    0.485542
std      1.888371   14.671782    1.242361    1.567175    0.350936    0.500092
min      0.000000   18.000000    1.000000    1.000000    1.000000    0.000000
25%      4.000000   46.000000    2.000000    1.000000    3.000000    0.000000
50%      4.000000   57.000000    3.000000    3.000000    3.000000    0.000000
75%      5.000000   66.000000    4.000000    4.000000    3.000000    1.000000
max     55.000000   96.000000    4.000000    5.000000    4.000000    1.000000

          BI-RADS         Age       Shape      Margin     Density      Target
count  830.000000  830.000000  830.000000  830.000000  830.000000  830.000000
mean     4.393976   55.781928    2.781928    2.813253    2.915663    0.485542
std      1.888371   14.671782    1.242361    1.567175    0.350936    0.500092
min      0.000000   18.000000    1.000000    1.000000    1.000000    0.000000
25%      4.000000   46.000000    2.000000    1.000000    3.000000    0.000000
50%      4.000000   57.000000    3.000000    3.000000    3.000000    0.000000
75%      5.000000   66.000000    4.000000    4.000000    3.000000    1.000000
max     55.000000   96.000000    4.000000    5.000000    4.000000    1.000000

** Do the Train Test Split** using test size 0.3

In [51]:
x=df.drop('Target',axis=1)
y=df.Target
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3, random_state=2)

In [52]:
xtrain

     BI-RADS  Age  Shape  Margin  Density
809        4   48      4       4        3
16         5   45      4       5        3
660        4   62      3       3        3
580        4   62      2       4        3
496        5   47      4       5        3
..       ...  ...    ...     ...      ...
534        4   38      4       1        3
584        6   41      2       1        3
493        4   55      1       1        3
527        4   28      2       1        3
168        4   46      1       1        3

[581 rows x 5 columns]

In [53]:
xtest

     BI-RADS  Age  Shape  Margin  Density
683        5   75      4       5        3
304        5   69      4       3        3
398        5   45      2       4        3
164        4   63      4       4        3
209        5   55      4       5        4
..       ...  ...    ...     ...      ...
176        4   32      1       1        3
572        4   73      2       1        3
58         5   54      4       4        3
152        5   54      2       1        3
312        5   70      4       3        3

[249 rows x 5 columns]

In [54]:
ytest

683    1
304    1
398    0
164    1
209    1
      ..
176    0
572    0
58     1
152    1
312    1
Name: Target, Length: 249, dtype: int64

### Decision Tree
**Importing decision tree classifier and create its instance**

In [55]:
from sklearn import set_config
set_config(print_changed_only=False)

In [56]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

**Fit the training data to the model**

In [58]:
dt.fit(xtrain,ytrain)
print(dt)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=None, splitter='best')

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

**What is the Score of the model?**

In [59]:
dt.score(xtest, ytest)

0.7269076305220884